[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
curachain = "J6DDahS4mKkJwJ6i7dcqmhj1oRVxCd1nLPwWF6Bhjyf5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ayman10/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
