[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
curachain = "GadKQ2cTG19siDDAmvVqdnTBKFrvMLSbU2x3hSXGU6G2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aymanf10/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
